import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToGenerativePart = (base64Data: string) => {
  // e.g., "data:image/jpeg;base64,LzlqLzRBQ..." -> { mimeType: "image/jpeg", data: "LzlqLzRBQ..." }
  const match = base64Data.match(/^data:(.+);base64,(.+)$/);
  if (!match) {
    throw new Error("Invalid base64 data URL");
  }
  const [_, mimeType, data] = match;
  return {
    inlineData: {
      mimeType,
      data,
    },
  };
};

export const createHugPhoto = async (childPhotoBase64: string, adultPhotoBase64: string): Promise<string> => {
  try {
    const childPart = fileToGenerativePart(childPhotoBase64);
    const adultPart = fileToGenerativePart(adultPhotoBase64);

    const prompt = `Using the two provided images, create a new, heartwarming photo. In the new photo, the adult from the second image should be hugging the child from the first image. The style should be realistic and touching, as if it's a real photograph of a tender moment between the adult and their younger self. Maintain the likeness of the person from both photos.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          childPart,
          adultPart,
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const firstPart = response.candidates?.[0]?.content?.parts?.[0];
    if (firstPart && firstPart.inlineData) {
      const base64ImageBytes: string = firstPart.inlineData.data;
      const mimeType = firstPart.inlineData.mimeType;
      return `data:${mimeType};base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("The AI model failed to generate an image. Please check the console for more details.");
  }
};